### ISSUE TITLE
Music doesn't stop

### ISSUE THREAD

**Issue by ItsMoorbinTime** [XRTG074TheDeveloper/DeepLethalGalactic#3]
Once the swarm starts and the music starts playing, it never stops. This persists when the ship is on orbit and when you next land.

**Comment by XRTG074TheDeveloper** [comment]
Hi there! Thanks for your report!

Just wanted to say that this bug is already fixed but the patch is not published because during tests I've mentioned another critical bug related to the swarm system and I want to upload them as a single patch

Have a WE'RE RICH day!
